export const TERMS_AND_CONDITIONS = [
    "These terms and conditions apply to all purchases made and services rendered within DHANNUMAL STORES and its online platforms.",
    "By entering our store or making a purchase, you agree to abide by these terms and conditions.",
    "DHANNUMAL STORES reserves the right to amend these terms and conditions at any time without prior notice. The updated terms will be effective upon posting in-store or on our website.",
    "While we strive for accuracy, prices displayed are subject to change without notice. The price charged will be the price at the register at the time of purchase.",
    "We accept Cash & UPI only. We do not accept any personal checks, foreign currency, debit cards, credit cards etc.",
    "In the event of a billing error, please notify customer service/Cash counter immediately. We will rectify any verified errors promptly.",
    "Discounts, promotions, and special offers are subject to their own specific terms and conditions and validity periods. They cannot be combined unless explicitly stated.",
    "Perishable Goods: Due to the nature of perishable goods (bread, buns, ice cream etc.), returns are generally not accepted unless the item is found to be spoiled or defective at the time of purchase or delivery. Must be reported within 1-2 hours of purchase and with proof of purchase.",
    "Returns of non-perishable, unopened, and undamaged items may be accepted within 3 days of purchase with a valid receipt. Refunds will be issued in the suitable form of payment. Some items like personal hygiene products, kuttu aata may be non-returnable for health and safety reasons.",
    "If an item is found to be defective or damaged upon purchase, please notify us immediately for an exchange or refund. Proof of purchase is required.",
    "Returns or exchanges without a valid receipt may be at the discretion of the store and may only be offered as store credit.",
    "We endeavor to provide accurate product information, but cannot guarantee that all descriptions, images, and specifications are entirely error-free. Packaging may vary.",
    "All products are subject to availability. While we try to maintain sufficient stock, we cannot guarantee that all items will always be in stock. We reserve the right to limit quantities.",
    "Customers are responsible for reviewing product labels for allergen information. While we take precautions, cross-contamination can occur in a retail environment.",
    "For your safety and security, CCTV cameras may be in operation throughout the store. Please report any suspicious activity to staff.",
    "Dhannumal Stores or any of its employees are not responsible for any lost, stolen, or damaged personal belongings.",
    "We expect all customers to treat staff and other customers with respect. Abusive, disruptive, or discriminatory behavior will not be tolerated and may result in removal from the premises.",
    "Unauthorized distribution of flyers, or commercial photography/videography is prohibited on store premises.",
    "Online orders are subject to acceptance and availability. We reserve the right to refuse or cancel an order for any reason and not state the reason.",
    "Estimated delivery times are provided as a guide and are not guaranteed. Delays may occur due to unforeseen circumstances.",
    "It is the customer's responsibility to ensure someone is available to receive and inspect the delivery. Any discrepancies or damages must be reported at the time of delivery.",
    "Delivery fees, if applicable, will be clearly communicated at the time of order placement.",
    "We collect personal data necessary for processing transactions, order fulfillment, and improving our services. Please refer to our Privacy Policy for details. Your data will be used in accordance with our Privacy Policy and applicable data protection laws.",
    "These terms and conditions are governed by the laws of Uttar Pradesh.",
    "Any disputes arising from these terms and conditions will first be attempted to be resolved amicably through discussion. If a resolution cannot be reached, disputes may be subject to the exclusive jurisdiction of the courts of Chandausi, Distt. Sambhal India.",
    "Dhannumal Stores is not liable for any indirect, incidental, special, or consequential damages arising from the use of its products or services, except where prohibited by law."
];